server:
  port: 8080
  error:
    include-stacktrace: always
  servlet:
    context-path: /mq

spring:
  application:
    name: rocketmq-producer

logging:
  level:
    com.bing.lan.rocketmq: debug


